name: youtube_player
description: A flutter plugin to play Youtube Videos "inline" without API Key in range of Quality(240p, 360p, 480p, 720p and 1080p).
version: 3.1.0
author: Sarbagya Dhaubanjar <mail@sarbagyastha.com.np>
homepage: https://github.com/sarbagyastha/youtube_player

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  share: ^0.6.0


flutter:
  uses-material-design: true

  plugin:
    androidPackage: np.com.sarbagyastha.youtubeplayer
    pluginClass: YoutubePlayerPlugin


